i-aka5h/Hack-October

- Programs/Python codes/colorama-module.py
- Programs/Python codes/gcd.py
File 1- It is an implementation of Colorama Module which produces colored terminal texts and courser.
File 2- Finds the Greatest Common Divisor of any given number.
> Added two useful files in Python

- Projects/Battery Notifier.py
Notifies you when the battery is low and charger not plugged && if battery is high and charger is plugged in
> Create Battery Notifier.py

- Projects/JavaScript/WeatherProject/app.js
- Projects/JavaScript/WeatherProject/index.html
The frontend part of the website is incomplete but will fix it later 
Please merge this pr with the hacktoberfest-accepted label
> Added a weather project

- Programs/Python codes/Website Blocker.py
Blocks the website from getting opened when you run the file
> Create Website Blocker.py

- MachineLearningModels/decision tree/Iris_Decisiontree.ipynb
#31 
add iris data classification model using decision tree algorithm.
> ml model iris dataset using decision tree

- Projects/JavaScript/Beginner Snake Game.js
Basic Snake Game for Beginnerse
> Create Beginner Snake Game.js

- Programs/Java Codes/Copy_List_with_Random _Pointer.java
Added Copy_List_with_Random _Pointer.java
> Create Copy_List_with_Random _Pointer.java

- MachineLearningModels/IRIS_Classification.ipynb
Machine Learning model to classify iris flower dataset
> iris flower image classification

- Programs/Python codes/menu-driven-binary-operations.py
- Projects/internetspeedtester/README.md
- Projects/internetspeedtester/internetspeedtest.py
- Projects/internetspeedtester/requirements.txt
Hey I have added internet speed tester code in python in projects folder and binary file editor in programs folder pls check 
Resolved #48
> Added internet speed test and binary file editor

- Programs/Python codes/snake-game.py
Added a snake game program in python
> Added snake game

- Programs/Java Codes/TwoPointerSorting.java
Added sorting of 0s 1s 2s using two pointer sorting algorithm in java
> Added TwoPointerSorting

- Contribute.md
Created a Contribue.md file.
This file consists of steps on how to contribute a project to this repository.
> Created a Contribue.md file for the steps on how to contribute

- Programs/Java Codes/MooresAlgo.java
Added Moore's Algorithm to calculate highest repeating element in an array.
> Added Moore's Algorithm

- Machine-Learning-Models/KMeans Clustering/kmeans_clustering.py
Added a KMeans Clustering code written in Python.
> Added KMeans Clustering code

- Projects/JavaScript/QuizApp/index.html
- Projects/JavaScript/QuizApp/script.js
- Projects/JavaScript/QuizApp/style.css
> Quiz App created

- Machine-Learning-Models/decision tree/MY Logistic Regression.ipynb
Logistic Regression Model used for classification problem
> Logistic Regression Model Added

- Projects/HandGestureDetetector/README.md
- Projects/HandGestureDetetector/main.py
- Projects/HandGestureDetetector/requirements.txt
Hi @i-aka5h Please check and merge this PR.
Issue - #94 
Thank you
> Add HandDetector

- Days between two dates/index.html
- Days between two dates/script.js
- Days between two dates/style.css
Hello @i-aka5h I successfully created project to find out number of days between two particular dates entered by user.
> Calculate Number of days between two dates

- Projects/Coffee Menu/coffee menu/coffee.html
- Projects/Coffee Menu/coffee menu/styles.css
I Have Added a cat dog recognition model using CNN.
> added-catDogModel

- Machine-Learning-Models/Spam_SMS_detection.py.ipynb
- Machine-Learning-Models/sms_data.csv
I have uploaded the program for Issue number #139 . Pls check it
> Spam SMS Detection 

- Projects/Age Calculator/Age _Calculator.html
I have added a age calculator .
> added-age-calculator

- Projects/CALCULATOR/calci.html
I have added a simple calculator.
> added-casio
